name: Conventional commits

on:
  pull_request:
  merge_group:

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup commitlint
      run: |
        npm install -g @commitlint/{cli,config-conventional}
        echo "export default { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js
    
    - name: Test commit message
      run: |
        npx commitlint --edit ${{ github.sha }}
