name: Conventional commits

on:
  pull_request:
  merge_group:

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup commitlint
      run: |
        npm install -g @commitlint/config-conventional @commitlint/cli
    
    - name: Validate last commit
      run: |
        npx commitlint --extends '@commitlint/config-conventional' --last --verbose

    - name: Validate all PR commits
      if: github.event_name == 'pull_request'
      run: npx commitlint --extends '@commitlint/config-conventional' --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
