name: Release published

on:
  release:
    types: [published]

jobs:
  release-published:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub event
        run: echo ${{ toJson(github) }}
