name: "Test skip/cancel behaviour"

on:
  workflow_dispatch:
    inputs:
      skip_build_tag_push_lambda_images:
        type: boolean
        description: "Skip lambda build"
      fail_build_tag_push_lambda_images:
        type: boolean
        description: "Fail lambda build"        
      fail_update_lambda_function_image:
        type: boolean
        description: "Fail update lambdas"

jobs:
  terragrunt-apply-ecr-only:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Running terragrunt-apply-ecr-only"

  build-tag-push-lambda-images:
    needs: terragrunt-apply-ecr-only
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip_build_tag_push_lambda_images }}
    steps:
      - name: Echo
        run: echo "Running build-tag-push-lambda-images"

      - name: Fail
        if: ${{ inputs.fail_build_tag_push_lambda_images }}
        run: exit 1

  terragrunt-apply-all-modules:
    needs: build-tag-push-lambda-images
    if: ${{ !failure() && !cancelled() }}
    runs-on: ubuntu-latest
    steps:
        - name: Sleep
          run: sleep 10
   
        - name: Echo
          run: echo "Running terragrunt-apply-all-moduless"

  update-lambda-function-image:
    needs: terragrunt-apply-all-modules
    runs-on: ubuntu-latest
    steps:
        - name: Echo
          run: echo "update-lambda-function-image"

        - name: Fail
          if: ${{ inputs.fail_update_lambda_function_image }}
          run: exit 1

  notify-on-error:
    needs:
      [
        terragrunt-apply-ecr-only,
        build-tag-push-lambda-images,
        terragrunt-apply-all-modules,
        update-lambda-function-image,
      ]
    if: ${{ failure() && !cancelled() }}
    runs-on: ubuntu-latest
    steps:
        - name: Echo
          run: echo "notify-on-error"