name: "Terragrunt apply"

on:
  push:
    branches:
      - "main"
    paths:
      - "version.txt"

permissions:
  id-token: write
  contents: read

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}    
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
  
      - name: Get version to deploy
        id: get-version
        uses: ./.github/workflows/get-version
        with:
          is-tagged: 'true'

  # We deploy ECR first to make sure it is available for the 'build-tag-push-lambda-images' job which will be run in parallel with `terragrunt-apply-all-modules`
  terragrunt-apply-ecr-only:
    needs: get-version
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.get-version.outputs.version }}    
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ env.VERSION }}

      - name: Get ref name
        run: git branch --show-current

      - name: Cat readme
        run: cat README.md

  build-tag-push-lambda-images:
    needs: [get-version, terragrunt-apply-ecr-only]
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.get-version.outputs.version }}
    strategy:
      fail-fast: false
      matrix:
        image: [audit-logs, audit-logs-archiver]
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ env.VERSION }}
      - name: Get ref name
        run: git branch --show-current

      - name: Cat readme
        run: cat README.md

  terragrunt-apply-all-modules:
    needs: [get-version, build-tag-push-lambda-images]
    if: ${{ !failure() && !cancelled() }}
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.get-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ env.VERSION }}

      - name: Get ref name
        run: git branch --show-current

      - name: Cat readme
        run: cat README.md

  update-lambda-function-image:
    needs: [get-version, terragrunt-apply-all-modules]
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.get-version.outputs.version }}
    strategy:
      fail-fast: false
      matrix:
        image: [audit-logs, audit-logs-archiver]
    steps:
      - name: Get ref name
        run: git branch --show-current

      - name: Cat readme
        run: cat README.md
