name: "Terragrunt plan"

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "version.txt"   

permissions:
  id-token: write
  contents: read

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}    
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      
      - name: Get version to deploy
        id: get-version
        uses: ./.github/workflows/get-version
        with:
          is-tagged: ${{ !startsWith(github.head_ref, 'release-please--') }} # If not the release PR branch, assume it is a revert PR

  detect-lambda-changes:
    needs: get-version
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.get-version.outputs.version }}  
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ env.VERSION }}

      - name: Get ref name
        run: git branch --show-current

      - name: Cat readme
        run: cat README.md 

  test-lambda-code:
    needs: [get-version, detect-lambda-changes]
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.get-version.outputs.version }}
    strategy:
      fail-fast: false
      matrix:
        image: [audit-logs, audit-logs-archiver]
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ env.VERSION }}

      - name: Get ref name
        run: git branch --show-current

      - name: Cat readme
        run: cat README.md 

  build-lambda-images:
    needs: [get-version, detect-lambda-changes]
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.get-version.outputs.version }}
    strategy:
      fail-fast: false
      matrix:
        image: [audit-logs, audit-logs-archiver]
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ env.VERSION }}

      - name: Get ref name
        run: git branch --show-current

      - name: Cat readme
        run: cat README.md

  terragrunt-plan:
    needs: get-version
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.get-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ env.VERSION }}

      - name: Get ref name
        run: git branch --show-current

      - name: Cat readme
        run: cat README.md
