

  name: "Upload artifacts"

  on:
    workflow_dispatch:
  
  jobs:
    workflow-events:
      runs-on: ubuntu-latest
      steps:
        - name: Make artifacts
          run: |
            echo "one" > ${{ github.workspace }}/one.txt
            echo "two" > ${{ github.workspace }}/two.txt
  
        - name: Sanity test appspec and form viewer task definition
          uses: actions/upload-artifact@v3
          with:
            name: templates
            path: |
                ${{ github.workspace }}/one.txt
                ${{ github.workspace }}/two.txt         
  