name: "Test workflow events"

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  workflow-events:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dump GitHub event object
        run: echo ${{ toJson(github) }}

    #   - name: Notify Slack
    #     run: |
    #         json='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":":red: GitHub workflow failed: <${{ github.event.workflow_run.html_url }}|${{ github.event.workflow.name }}>"}}]}'
    #         curl -X POST -H 'Content-type: application/json' --data "$json" ${{ secrets.SLACK_WEBHOOK_URL }}
