name: "Test workflow events"

on:
  pull_request:
  workflow_dispatch:

jobs:
  workflow-events:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Notify Slack
        env:
          WORKFLOW_URL: "https://github.com/cds-snc/forms-terraform/actions/workflows/terragrunt-apply-production.yml"
          WORKFLOW_NAME: "Terragrunt apply PRODUCTION"
        run: |
          json='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":":red: GitHub workflow failed: <${{ env.WORKFLOW_URL }}|${{ env.WORKFLOW_NAME }}>"}}]}'      
          curl -X POST -H 'Content-type: application/json' --data "$json" ${{ secrets.SLACK_WEBHOOK_URL }}
